### ISSUE TITLE
Users can upvode / downvote multiple times

### ISSUE THREAD

**Issue by crpe** [Deadarius/SugoiOverflow#13]
1. Find an answer that has already been voted.
2. Upvote
3. Upvote againg. It's not working. But...
4. Downvote
5. Downvote again. You can do this until you get to 0.
6. Upvote.
7. Upvote again. You can upvote until you get to the initial number of votes + 1 (your vote)

**Comment by Sandy987** [comment]
I don't think this is an issue. You cannot have more than one upvote, nor can you have more than one downvote. This is intended.

**Comment by crpe** [comment]
I want to reopen the bug
